spring.application.name=chorely
spring.datasource.url=jdbc:mysql://localhost:3306/chorely_test
spring.datasource.username=test_user
spring.datasource.password=test_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
jwt.secret=c3VwZXItc2ltcGxlLWFuZC1zYWZlLWFuZC1sb25nLTI1Ni1iaXQtc2VjcmV0LWtleQ==
jwt.expiration.ms=86400000