spring.application.name=chorely
spring.datasource.url=${DB_DEV_URL:jdbc:mysql://localhost:3306/chorely}
spring.datasource.username=${DB_USER:dev}
spring.datasource.password=${DB_PASSWORD:dev}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=${SECRET_KEY:c2VjcmV0LWtleS1hdC1sZWFzdC0yNTYtYml0cy1sb25nLWVub3VnaC10by1iZS1iYXNlNjQtZW5jb2RlZA==}
jwt.expiration.ms=${JWT_EXPIRES_IN:86400000}