spring.application.name=chorely
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.secret=${SECRET_KEY}
jwt.expiration.ms=${JWT_EXPIRES_IN}